experiment:
  path_output_rec_performance: baselines_kars/{}/
  dataset: lastfm
  data_config:
    strategy: fixed
    train_path: ../data/{}/train2id.tsv
    test_path: ../data/{}/test2id.tsv
    side_information:
      - dataloader: ItemAttributes
        attribute_file: ../data/{}/map.tsv
        features: ../data/{}/features.tsv
  evaluation:
    simple_metrics: [MAP, Precision, MAR, Recall, F1, nDCG, Gini, ItemCoverage, EFD, EPC]
  top_k: 500
  gpu: 1
  models:

    # 4
    AttributeItemKNN:
      meta:
        save_recs: True
      loader: ItemAttributes
      neighbors: [500, 1000]
      similarity: ['cosine', 'dot']
      
    # 4
    ItemKNN:
      meta:
        save_recs: True
      neighbors: [500, 1000]
      similarity: ['cosine', 'dot']
      implementation: ['classical', 'euclidean']

    # 4
    UserKNN:
      meta:
        save_recs: True
      neighbors: [500, 1000]
      similarity: ['cosine', 'dot']
      implementation: ['classical', 'euclidean']

    # 4
    AttributeUserKNN:
      meta:
        save_recs: True
      loader: ItemAttributes
      neighbors: [500, 1000]
      similarity: ['cosine', 'dot']
      profile: binary
      
    # 2x2x2 = 8
    MultiVAE:
      meta:
        save_recs: True
      epochs: 30
      batch_size: 512
      intermediate_dim: [16, 32, 64]
      latent_dim: [16, 32, 64]
      reg_lambda: [0.01, 0.05]
      lr: 0.01
      dropout_pkeep: 1

    # 3x2x2 = 12
    CFGAN:
      meta:
        save_recs: True
      epochs: 30
      batch_size: 1024
      factors: [10, 20, 30]
      lr: 0.01
      l_w: 0.1
      l_b: 0.1
      l_gan: 0.1
      g_epochs: [2, 5]
      d_epochs: [2, 5]
      s_zr: 0.001
      s_pm: 0.001

    # 3x2x2 = 12
    NGCF:
      meta:
        save_recs: True
      lr: 0.01
      epochs: 30
      batch_size: 1024
      factors: [32, 64, 128]
      l_w: [0.05, 0.01]
      weight_size: [[(64,)], [(128,)]]
      node_dropout: ()
      message_dropout: (0.1,)
      n_fold: 5

    # 1
    KaHFM:
      meta:
        validation_rate: 1
        verbose: True
        save_recs: True
        validation_metric: nDCG@500    # must match top_k parameter
      loader: ItemAttributes
      epochs: 30
      batch_size: 1024
      lr: 0.01
      bias_regularization: 0
      user_regularization: 0.0025
      positive_item_regularization: 0.0025
      negative_item_regularization: 0.00025

    # 2x3 = 6
    LightGCN:
      meta:
        save_recs: True
      lr: 0.01
      epochs: 30
      batch_size: 1024
      factors: [32, 64, 128]
      l_w: 0.1
      n_layers: [1, 2, 3]
      n_fold: [2, 5]

    # 2x2x2 = 8
    NeuMF:
      meta:
        save_recs: True
      epochs: 30
      batch_size: 1024
      mf_factors: [5, 10]
      mlp_factors: [5, 10]
      mlp_hidden_size: (64,32,16)
      lr: 0.01
      dropout: [0.2, 0.4]
      is_mf_train: True
      is_mlp_train: True

    # 3 
    BPRMF:
      meta:
        save_recs: True
      epochs: 30
      factors: [10, 20, 30]
      lr: 0.01
      bias_regularization: 0
      user_regularization: 0.0025
      positive_item_regularization: 0.0025
      negative_item_regularization: 0.0025
      update_negative_item_factors: True
      update_users: True
      update_items: True
      update_bias: True

    # 3
    PureSVD:
      meta:
        save_recs: True
      factors: [10, 20, 30]
      seed: 42

    # 2x2 = 4
    Slim:
      meta:
        save_recs: True
      l1_ratio: [0.005, 0.01]
      alpha: [0.005, 0.01]

    # 1
    VSM:
      meta:
        save_recs: True
      loader: ItemAttributes
      similarity: cosine
      user_profile: binary
      item_profile: binary

