experiment:
  gpu: 1
  dataset: dbbook
  data_config:
    strategy: fixed
    train_path: ../data/{}/train2id.tsv
    test_path: ../data/{}/test2id_gen_baselines.tsv
    side_information:
      - dataloader: ItemAttributes
        attribute_file: ../data/{}/map.tsv
        features: ../data/{}/features.tsv
  evaluation:
    simple_metrics: [MAP, Precision, MAR, Recall, F1, nDCG, Gini, ItemCoverage, EFD, EPC]
    paired_ttest: False
    wilcoxon_test: False

  top_k: 10
  models:


    # # 8 = 2x2x2
    # ItemKNN:
    #   meta:
    #     save_recs: True
    #   neighbors: [50, 100, 150]
    #   similarity: ['cosine', 'dot']
    #   implementation: ['classical', 'euclidean']

    # # 8 = 2x2x2
    # UserKNN:
    #   meta:
    #     save_recs: True
    #   neighbors: [50, 100, 150]
    #   similarity: ['cosine', 'dot']
    #   implementation: ['classical', 'euclidean']

    # # 8 = 2x2x2
    # AttributeItemKNN:
    #   meta:
    #     save_recs: True
    #   loader: ItemAttributes
    #   neighbors: [50, 100, 150]
    #   similarity: ['cosine', 'dot']

    # # 8 = 2x2x2
    # AttributeUserKNN:
    #   meta:
    #     save_recs: True
    #   loader: ItemAttributes
    #   neighbors: [50, 100, 150]
    #   similarity: ['cosine', 'dot']
    #   profile: binary
      
    # 18 = 3x3x2
    MultiVAE:
      meta:
        validation_rate: 5
        save_recs: True
      epochs: 10
      batch_size: 512
      intermediate_dim: 600
      latent_dim: 200
      reg_lambda: 0.05
      lr: 0.0001
      dropout_pkeep: 1

    # 12 = 3x2x2
    CFGAN:
      meta:
        validation_rate: 5
        save_recs: True
      epochs: 10
      batch_size: 512
      factors: 10
      lr: 0.0001
      l_w: 0.5
      l_b: 0.001
      l_gan: 0.001
      g_epochs: 5
      d_epochs: 1
      s_zr: 0.001
      s_pm: 0.001

    BPRMF:
      meta:
        validation_rate: 5
        save_recs: True
      epochs: 10
      factors: 10
      lr: 0.0001
      bias_regularization: 0
      user_regularization: 0
      positive_item_regularization: 0
      negative_item_regularization: 0
      update_negative_item_factors: True
      update_users: True
      update_items: True
      update_bias: True




    # # 12 = 3x2x2
    # NGCF:
    #   meta:
    #     validation_rate: 10
    #     save_recs: True
    #   lr: 0.001
    #   epochs: 30
    #   batch_size: 512
    #   factors: 32
    #   l_w: 0.1

    # # 3
    # KaHFM:
    #   meta:
    #     validation_rate: 10
    #     verbose: True
    #     save_recs: True
    #     validation_metric: nDCG@10    # must match top_k parameter
    #   loader: ItemAttributes
    #   epochs: 30
    #   batch_size: 512
    #   lr: 0.001

    # # 8 = 2x2x2
    # NeuMF:
    #   meta:
    #     validation_rate: 10
    #     save_recs: True
    #   epochs: 30
    #   batch_size: 512
    #   mf_factors: 20
    #   mlp_factors: 20
    #   mlp_hidden_size: (64,32)
    #   lr: 0.001
    #   dropout: 0.2
    #   is_mf_train: True
    #   is_mlp_train: True

    # 5


    # 
    # PureSVD:
    #   meta:
    #     save_recs: True
    #   factors: [30, 40, 50]
    #   seed: 42

    # 
    # VSM:
    #   meta:
    #     save_recs: True
    #   loader: ItemAttributes
    #   similarity: cosine
    #   user_profile: binary
    #   item_profile: binary




    # 4 = 2x2
    # Slim:
    #   meta:
    #     save_recs: True
    #   l1_ratio: [0.005, 0.01]
    #   alpha: [0.005, 0.01]
    
    # # 2x3 = 6
    # LightGCN:
    #   meta:
    #     validation_rate: 10
    #     save_recs: True
    #   lr: 0.01
    #   epochs: 30
    #   batch_size: 1024
    #   factors: [32, 64, 128]
    #   l_w: 0.1
    #   n_layers: [1, 2, 3]
    #   n_fold: [2, 5]
      

    

    